name: Node CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 17.2.0
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: npm ci
    - run: npm test
    - run: npm run build
